# Generated by Django 4.1.2 on 2022-10-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(blank=True, related_name='product_variants', to='store.variant'),
        ),
    ]
