# Generated by Django 4.1.2 on 2022-10-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variant_stripe_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
